### ISSUE TITLE
Advanced scoring

### ISSUE THREAD

**Issue by maicol07** [axiel7/AniHyou-iOS#23]
**Request (required)**

Advanced scoring system, basically 5 scores which are saved on Anilist and generates the final score (I think it's an average score between all 5 scores)

**Examples**  
Anilist website:

![](https://github.com/axiel7/AniHyou-android/assets/9463142/1e94ccac-d8e3-4613-aa75-cc36055c8569)

**Comment by maicol07** [comment]
> @maicol07 if you refresh the list, it shows the correct mean score?

No, It's unscored

**Comment by axiel7** [comment]
That's weird, manually refreshing the list should show the new score. I'll check it

> Should I create a new issue for this in the Android repo?

Don't worry about that.

**Comment by maicol07** [comment]
Probably that's due to this where you get the main score:

https://github.com/axiel7/AniHyou-android/blob/3f9e726a78f5db5ffce82d2877221b14a5711374/app/src/main/java/com/axiel7/anihyou/ui/screens/usermedialist/composables/StandardUserMediaListItem.kt#L90

Probably the easiest fix is to replicate AniList behaviour, so adding the average calculation here and update the score state, then send all to AniList (including the average main score):

https://github.com/axiel7/AniHyou-android/blob/3f9e726a78f5db5ffce82d2877221b14a5711374/app/src/main/java/com/axiel7/anihyou/ui/screens/mediadetails/edit/EditMediaViewModel.kt#L42-L44

This way you also don't need to change the view; the score will also be visible from the website or other clients.

**Comment by axiel7** [comment]
Oh I see so it's the frontend that actually updates the mean score. I just fixed it in the latest commit, wait for the next beta version
