### ISSUE TITLE
Quickly give +1 to the progress of an anime or manga.

### ISSUE THREAD

**Issue by sawa-ko** [axiel7/AniHyou-iOS#25]
**Request (required)**
Currently to advance in the progress of an anime or manga is necessary to enter the detail of the same, then press the edit button and then advance +1 in the progress of the anime or manga. This is a bit tedious when you have a lot of anime at once.

**Additional context**
Add any other context or app screenshots about the feature request here.

**Examples**
For example, that in the list of anime and manga currently being watched there is a button for each one to add +1 to the progress of the same and also that by pressing and holding you can advance more than one by showing an assistant or with some gesture.

**Comment by axiel7** [comment]
You can swipe left (or right, you can change this in settings) the anime/manga item to quickly update +1 progress ;)
