### ISSUE TITLE
Custom List Support

### ISSUE THREAD

**Issue by CreeperGate** [axiel7/AniHyou-iOS#27]
Request:
Custom list support

Description:
I know that other apps have this, but would you mind not locking it behind a paywall?.

Other apps with this:
Anilistclient - paywall
Myanilist - paywall
I also heard AL-chan on android has this, but i dont have andoid.

**Comment by CreeperGate** [comment]
Just found another app with this
Anilime - free
Only thing is its unoffical so kinda sketch

**Comment by axiel7** [comment]
Yes I plan to add it (for free), but I don't know when

**Comment by axiel7** [comment]
FYI: latest TestFlight build has custom lists support
