### ISSUE TITLE
Nothing appearing properly in beta

### ISSUE THREAD

**Issue by CreeperGate** [axiel7/AniHyou-iOS#30]
The watching and reading sections have all anime and manga in them, some sections only have 2 anime in them even though they're supposed to be fill, etc.

Just happens with my app.

The watching section only shows watching, planning only planning, paused all my paused ones, etc...

Added a video

[my phone wont let me upload the video due to "private access" or whatever so heres a link](https://imgur.com/a/5skinpP)

 - Device model: iphone 14
 - OS version: ios 17.1.1
 - App version: 1.8.2 (60)

running on a beta build

**Comment by axiel7** [comment]
Are you perhaps sorting by title or popularity?

**Comment by CreeperGate** [comment]
I was doing it by title, and I tried every way, and it doesn't work any way and just glitches some other way.

**Comment by CreeperGate** [comment]
Worked after latest update, and you added the warnings to popularity and title, thanks
