### ISSUE TITLE
App crashes when open an anime

### ISSUE THREAD

**Issue by robdvins** [axiel7/AniHyou-iOS#31]
**Describe the bug (required)**
The application crashes when trying to open an anime. This only happens on certain animes, not all.

**To Reproduce**
1. Go to `Anime > Watching`
2. Click on some anime
3. See error

**Expected behavior**
Show anime info.

**Enviroment (required)**
 - Device model: iPhone 8
 - OS version: 16.7.10
 - App version: 1.8.3

**Additional context**
In some areas it works, for example in `Home > Discover >Winter 2025`.

**Comment by axiel7** [comment]
>  This only happens on certain animes, not all.

Could you tell me which one?

**Comment by robdvins** [comment]
> > This only happens on certain animes, not all.
> 
> Could you tell me which one?

These are some examples:

- [Oshi no Ko] 2nd Season
- Boku no Hero Academia 7
- Dead Dead Demon's Dededededestruction
- Giji Harem
- Kimi ni Todoke 3RD SEASON
- Mahou Shoujo ni Akogarete
- Make Heroine ga Oosugiru!
- Megami no Café Terrace 2nd Season
- ONE PIECE
- Ookami to Koushinryou: MERCHANT MEETS THE WISE WOLF
- Shikanoko Nokonoko Koshitantan
- Tensei Shitara Slime Datta Ken 3rd Season
- Tokidoki Bosotto Russiago de Dereru Tonari no Alya-san

**Comment by axiel7** [comment]
Okay, could you try the [TestFlight](https://testflight.apple.com/join/Om3OIlKd) version?

**Comment by robdvins** [comment]
Looks perfect, no crashes! 😁
