### ISSUE TITLE
Customizable default opening tab

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-iOS#33]
**Request (required)**
As I requested for the android version of AniHyou, now I switched to iOS so I would like to have an option in settings menu to choose which tab should be opened when the app starts

**Comment by fraluc06** [comment]
@axiel7 let me know if it's possible to reproduce the request on the IOS version

**Comment by axiel7** [comment]
Yes I'll implement it, make sure to join TestFlight and wait :)

**Comment by fraluc06** [comment]
Thank you I’ll wait. I’ve tried almost all anilist clients but imo yours is the best!

**Comment by axiel7** [comment]
Thank you! Check latest TestFlight version ;)
