### ISSUE TITLE
Open entry tab when an area is clicked

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-iOS#34]
I was thinking of a new feature: when you click the area of the entry (this part)
![IMG_0219](https://github.com/user-attachments/assets/99787cde-ae12-4640-9ff7-ee04999881ff) it will open the editing mode of the entry 
![IMG_0218](https://github.com/user-attachments/assets/c9685b61-c8ac-4503-98f4-90ded5adafe9)
Instead when you click the thumbnail of the anime/manga the info tab will open
![IMG_0217](https://github.com/user-attachments/assets/d9f3b5a7-6f5e-42a1-92e9-e1f99a95e7d6
Do you think it’s a useful feature or it could be a bit confusing and it’s only a thing I world like to have?
@axiel7

**Comment by axiel7** [comment]
I don't like this idea. You can already swipe left to open the edit sheet:
![IMG_2E00BA4F335C-1](https://github.com/user-attachments/assets/e51fa88d-6bb2-4317-a6e6-0ae55a642154)

**Comment by fraluc06** [comment]
Ok, thank you anyway for reading my request
