### ISSUE TITLE
Titles not translated correctly in beta

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-iOS#36]
In the beta version of the app (with the normal version idk because I haven’t installed it, but I think its the same), these titles in the home tab are not translated even if in the translation page all the strings are translated and approved in my langiage (Italian) here’s a screenshot
![IMG_0237](https://github.com/user-attachments/assets/95641a31-7ad7-4283-a10b-8e66255db152)
![IMG_0238](https://github.com/user-attachments/assets/2fe98173-b4d3-4917-acd0-30c625a9e104)

**Comment by axiel7** [comment]
Thanks for the reminder, I forgot to import new strings
