### ISSUE TITLE
App not saving completed state properly

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-iOS#37]
**Describe the bug (required)**
I experienced a bug when saving an entry that I finished watching, in fact when I do that, the app doesn’t save the start date, only the finishing date. I also tried modifying and re apply the start date but I have the same behaviour, so I have to edit the entry going to Anilist site
 - Device model: 
 - OS version: iOS 18.1.1
 - App version: latest beta  1.8.5

**Comment by axiel7** [comment]
Check if the new TestFlight build 83 fixes it

**Comment by fraluc06** [comment]
Thanks, now the issue seems to be fixed
