### ISSUE TITLE
Automatically detect start date when an entry is set to “watching”

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-iOS#38]
**Request (required)**
I would like to request that the app automatically sets the start date when you select watching in an anime tab, this behaviour happens when you set an entry as completed but it would be useful to have the same thing when you start. Just to avoid 2 clicks.
@axiel7

**Comment by fraluc06** [comment]
Uhm, I noticed that I have the behaviour described in my first comment, only if I increment the watched episodes number, but this doesn’t apply to the watching state itself. I made this video, the app is in Italian as it’s my primary language but I hope it can be helpful


https://github.com/user-attachments/assets/5628f291-0a40-4e62-ae3d-dcadd16cdda9

**Comment by axiel7** [comment]
Check latest TestFlight build 84 :)

**Comment by fraluc06** [comment]
Thank you! Now it works perfectly, it wasn’t a real problem but just a quality of life improvement. I want your app to be more awesome than it already is 😁
