### ISSUE TITLE
Set to max the episodes counter when anime is set to completed

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-iOS#39]
I’m sorry to open a new issue so soon, but I’d like to have the episode counter go to max value for an anime when it’s set to completed (maybe I’m wrong but in the past I remember I used this functionality but I also checked past beta builds and the official stable release but nothing)
@axiel7

**Comment by axiel7** [comment]
Sure no problem.

Right now it works the other way. It sets to completed after incrementing the progress
