### ISSUE TITLE
Sync error of initial dates of watching

### ISSUE THREAD

**Issue by fraluc06** [axiel7/AniHyou-iOS#41]
I was to set an anime to completed in my list and I realised that the app erased the start date the strange thing is that when I realised that, I didn’t saved changes, so this have to be happened previously, when I updated the entry, some time ago

**Comment by fraluc06** [comment]
I found the problem: this is caused by the quick add of an episode when you swipe an anime in the list, it adds an episode to the watched episodes counter but it also overrides the start date to the one that is when you quick add

**Comment by axiel7** [comment]
Which app version are you using? (Check it in Profile -> Settings -> Information)

**Comment by axiel7** [comment]
Sorry I didn't tested it 🙃, check the new beta build

**Comment by fraluc06** [comment]
I haven’t tested the quick add when it’s the last episode 😅
The other thing instead, seems to work, thx
